### ISSUE TITLE
torch::tensor.clone()

### ISSUE THREAD

**Issue by soldierofhell** [mhubii/libtorch_custom_dataset#1]
Hi, got question to custom_dataset.h: why in get() function you return clone() (copy) of tensors? Is it really necessary?
Regards,

**Comment by mhubii** [comment]
hi @soldierofhell , I changed the code a little. The problem here is that if you load an image with torch::from_blob, torch doesn't own the data, so it gets thrown away after get() was called. But you have a point here, thanks for the hint :D
