### ISSUE TITLE
have a  problem  in    x = torch::relu(torch::max_pool2d(conv1(x), 2));

### ISSUE THREAD

**Issue by WuLoing** [mhubii/libtorch_custom_dataset#2]
![图片](https://user-images.githubusercontent.com/13691288/63559972-a5d4ff80-c586-11e9-9f28-a08812ac8002.png)

**Comment by WuLoing** [comment]
input  tensor is empty.The setting of dataset path  is wrong!

**Comment by mhubii** [comment]
are you using windows?
